
WIDTH = 1000
HEIGHT = 800
FPS = 60

CONTAINER_WIDTH = 50
CONTAINER_HEIGHT = 50

CONTAINER_BORDER_RATIO = 0.85

INSIDE_HEIGHT = CONTAINER_WIDTH * CONTAINER_BORDER_RATIO
INSIDE_WIDTH = CONTAINER_HEIGHT * CONTAINER_BORDER_RATIO

TUBE_WIDTH = 1
